//! 生成自定义 vpnc-script
//!
//! openconnect 把路由/DNS 的配置完全交给 `--script` 指定的脚本，
//! 这正是我们实现分流的抓手：把「默认路由是否走 VPN」这个唯一的开关拿在自己手里。
//!
//! 结论来自机器上那份验证可用的官方脚本：
//! - 用 `TUNIDX`（网卡索引）而不是网卡名，避免中文系统下名字匹配不上；
//! - 隧道场景下把接口网关设成**隧道自己的地址**即可，不要用「网络地址 + 1」；
//! - DNS 必须带 `validate=no`，否则 Windows 会去连一次 DNS 服务器并卡 10 秒；
//! - 接口地址与 DNS 都要带 `store=active`，不要落进持久化配置。
//!
//! 脚本只负责「把网卡准备好」并把关键参数回报给 worker，分流规则由 worker 统一下发。

use std::path::Path;

use crate::vpn::models::VpnMode;

/// 脚本回报给 worker 的标记前缀
pub const MARKER: &str = "WS-TOOLS";

/// 生成脚本时需要烘焙进去的固定参数
pub struct ScriptContext<'a> {
    pub session_dir: &'a Path,
    pub mode: VpnMode,
    pub use_vpn_dns: bool,
    /// 连接前的物理网关，用于给 VPN 服务器本身加主机路由避免环路
    pub original_gateway: &'a str,
}

/// 生成 Windows 用的 JScript 脚本（openconnect 在 Windows 上用 cscript 执行 .js）
pub fn windows_script(ctx: &ScriptContext) -> String {
    let session_dir = escape_js_string(&ctx.session_dir.to_string_lossy());
    let mode = match ctx.mode {
        VpnMode::CustomerFirst => "customer_first",
        VpnMode::CompanyFirst => "company_first",
    };
    let use_vpn_dns = if ctx.use_vpn_dns { "true" } else { "false" };
    // 烘焙成独立常量，避免在生成结果里做「分支是否存在」这类脆弱断言
    let set_gateway = if ctx.mode == VpnMode::CompanyFirst {
        "true"
    } else {
        "false"
    };
    let original_gw = escape_js_string(ctx.original_gateway);

    // JScript 是 ES3，没有模板字符串 / const / trim，全部用字符串拼接和 var
    // 这份 JScript 必须是纯 ASCII：cscript.exe 在文件没有 BOM 时按系统 ANSI
    // 代码页（中文 Windows 即 GBK）读取 .js。只要出现一个非 ASCII 字节，中文注释
    // 之后的代码就会被解码错位，脚本直接以 "JavaScript compilation error: Syntax
    // error" 退出 1，而 cscript 的报错又回不到 openconnect 的管道里，现场只留下一句
    // 语焉不详的 "Failed to spawn script"。
    let body = r#"// Generated by ws-tools. Do not edit manually.
// Split-tunnel mode: __MODE__

var MODE = "__MODE__";
// Whether the VPN interface takes the default route: true in company-first mode
var SET_GATEWAY = __SET_GATEWAY__;
var USE_VPN_DNS = __USE_VPN_DNS__;
var SESSION_DIR = "__SESSION_DIR__";
var ORIGINAL_GW = "__ORIGINAL_GW__";

var accumulatedExitCode = 0;
var ws = WScript.CreateObject("WScript.Shell");
var env = ws.Environment("Process");
var comspec = ws.ExpandEnvironmentStrings("%comspec%");

function run(cmd) {
    var fullCmd = comspec + " /C \"" + cmd + "\" 2>&1";
    var oExec = ws.Exec(fullCmd);
    oExec.StdIn.Close();
    var s = oExec.StdOut.ReadAll();
    accumulatedExitCode += oExec.ExitCode;
    return s;
}

function appendLog(text) {
    try {
        var fso = WScript.CreateObject("Scripting.FileSystemObject");
        var f = fso.OpenTextFile(SESSION_DIR + "\\script.log", 8, true);
        f.WriteLine(text);
        f.Close();
    } catch (e) {}
}

// openconnect starts us with bInheritHandles=FALSE, so our stdout is not wired
// to the worker's pipe. Reporting therefore has to go through script.log in the
// session directory. stdout is kept only for manual debugging, and a failure
// there must never break the main flow.
function report(key, value) {
    var line = "WS-TOOLS " + key + "=" + value;
    try { WScript.echo(line); } catch (e) {}
    appendLog(line);
}

var reason = env("reason") || "";
var tundev = env("TUNDEV") || "";
var tunidx = env("TUNIDX") || "";
var ip4 = env("INTERNAL_IP4_ADDRESS") || "";
var mask4 = env("INTERNAL_IP4_NETMASK") || "255.255.255.255";
var mtu = env("INTERNAL_IP4_MTU") || "";
var dns = env("INTERNAL_IP4_DNS") || "";
var vpngw = env("VPNGATEWAY") || "";

// netsh interface argument: prefer the index, fall back to a quoted name.
// Interface names on Chinese Windows are not safe to put on a command line.
var tunRef = tunidx !== "" ? tunidx : ("\"" + tundev + "\"");

if (reason == "connect") {
    report("reason", "connect");
    report("mode", MODE);
    report("tunidx", tunidx);
    report("tundev", tundev);
    report("ip4", ip4);
    report("mask", mask4);
    report("mtu", mtu);
    report("dns", dns);
    report("vpngw", vpngw);

    if (mtu !== "") {
        run("netsh interface ipv4 set subinterface " + tunRef + " mtu=" + mtu + " store=active");
    }

    // The one real decision: does the VPN interface get the default route?
    if (SET_GATEWAY) {
        // Company-first: drop the interface metric to 1 and point its gateway at
        // the tunnel's own address, so Windows installs a default route through
        // the tunnel that outranks the physical adapter's.
        run("netsh interface ip set interface " + tunRef + " metric=1 store=active");
        run("netsh interface ip set address " + tunRef + " static " + ip4 + " " + mask4 +
            " " + ip4 + " gwmetric=1 store=active");
    } else {
        // Customer-first: no gateway, and raise the interface metric so Windows
        // never picks this tunnel over the physical adapter. Only the company
        // subnets pushed down by the worker actually enter the tunnel.
        run("netsh interface ip set interface " + tunRef + " metric=900 store=active");
        run("netsh interface ip set address " + tunRef + " static " + ip4 + " " + mask4 +
            " store=active");
    }

    // Host route to the VPN server itself, reached via the physical gateway, so
    // tunnel traffic is not swallowed by the tunnel and cannot loop.
    if (vpngw !== "" && ORIGINAL_GW !== "") {
        if (vpngw.indexOf(":") >= 0) {
            run("netsh interface ipv6 add route " + vpngw + "/128 \"" + ORIGINAL_GW + "\" store=active");
        } else {
            run("route add " + vpngw + " mask 255.255.255.255 " + ORIGINAL_GW);
        }
    }

    if (USE_VPN_DNS && dns !== "") {
        run("netsh interface ipv4 delete dnsservers " + tunRef + " all");
        var list = dns.split(" ");
        for (var i = 0; i < list.length; i++) {
            if (list[i] !== "") {
                // validate=no is mandatory: without it Windows probes DNS
                // reachability first and blocks for about 10 seconds.
                run("netsh interface ipv4 add dnsservers " + tunRef + " " + list[i] + " validate=no");
            }
        }
        // Lower the interface metric so the system resolves through the company
        // DNS first. This does not affect split tunnelling because there is no
        // default route on this interface.
        run("netsh interface ip set interface " + tunRef + " metric=5 store=active");
        report("dns_applied", dns);
    }

    report("done", "connect");
    WScript.Quit(0);
}

if (reason == "disconnect") {
    report("reason", "disconnect");

    if (vpngw !== "") {
        if (vpngw.indexOf(":") >= 0) {
            run("netsh interface ipv6 delete route " + vpngw + "/128\n");
        } else {
            run("route delete " + vpngw + " mask 255.255.255.255");
        }
    }
    if (ip4 !== "") {
        run("netsh interface ipv4 delete address " + tunRef + " " + ip4 + " gateway=all");
    }

    report("done", "disconnect");
    WScript.Quit(0);
}

WScript.Quit(0);
"#;

    body.replace("__MODE__", mode)
        .replace("__SET_GATEWAY__", set_gateway)
        .replace("__USE_VPN_DNS__", use_vpn_dns)
        .replace("__SESSION_DIR__", &session_dir)
        .replace("__ORIGINAL_GW__", &original_gw)
}

/// 生成 macOS 用的 POSIX shell 脚本
pub fn macos_script(ctx: &ScriptContext) -> String {
    let session_dir = escape_sh_string(&ctx.session_dir.to_string_lossy());
    let mode = match ctx.mode {
        VpnMode::CustomerFirst => "customer_first",
        VpnMode::CompanyFirst => "company_first",
    };
    let use_vpn_dns = if ctx.use_vpn_dns { "1" } else { "0" };
    let original_gw = escape_sh_string(ctx.original_gateway);
    // 「以公司网络为主」必须由脚本把默认路由从物理网关抢到隧道，否则
    // 隧道建好了也没有任何流量走 VPN，界面显示「已连接」但公司网络不通。
    let set_gateway = if ctx.mode == VpnMode::CompanyFirst {
        "1"
    } else {
        "0"
    };

    let body = r#"#!/bin/sh
# 由 ws-tools 自动生成，请勿手工修改
# 分流模式: __MODE__

MODE="__MODE__"
SET_GATEWAY=__SET_GATEWAY__
USE_VPN_DNS=__USE_VPN_DNS__
SESSION_DIR="__SESSION_DIR__"
ORIGINAL_GW="__ORIGINAL_GW__"

report() {
    LINE="WS-TOOLS $1=$2"
    echo "$LINE"
    echo "$LINE" >> "$SESSION_DIR/script.log" 2>/dev/null
}

# 找出当前默认路由所在网卡对应的「网络服务」显示名（如「Wi-Fi」），
# networksetup 只认这个名字，不认网卡名。
# 必须在默认路由被隧道接管之前调用：接管后再问 route get default 拿到的是 utun，
# networksetup 里根本没有这个服务，DNS 会静默写不进去。
resolve_physical_service() {
    PHYSICAL_IF=$(/sbin/route -n get default 2>/dev/null | /usr/bin/awk '/interface:/{print $2}')
    PHYSICAL_SERVICE=""
    if [ -n "$PHYSICAL_IF" ]; then
        PHYSICAL_SERVICE=$(/usr/sbin/networksetup -listnetworkserviceorder 2>/dev/null \
            | /usr/bin/grep -B 1 "Device: $PHYSICAL_IF" \
            | /usr/bin/head -n 1 \
            | /usr/bin/sed -E 's/^\([0-9]+\)[[:space:]]*//')
    fi
}

reason="${reason:-}"

if [ "$reason" = "connect" ]; then
    report reason connect
    report mode "$MODE"
    report tundev "${TUNDEV:-}"
    report ip4 "${INTERNAL_IP4_ADDRESS:-}"
    report mask "${INTERNAL_IP4_NETMASK:-}"
    report mtu "${INTERNAL_IP4_MTU:-}"
    report dns "${INTERNAL_IP4_DNS:-}"
    report vpngw "${VPNGATEWAY:-}"

    # 配置 utun 接口地址。openconnect 通常已经做过一次，重复执行是幂等的。
    if [ -n "${INTERNAL_IP4_ADDRESS:-}" ]; then
        if [ -n "${INTERNAL_IP4_MTU:-}" ]; then
            /sbin/ifconfig "$TUNDEV" inet "$INTERNAL_IP4_ADDRESS" "$INTERNAL_IP4_ADDRESS" \
                netmask "$INTERNAL_IP4_NETMASK" mtu "$INTERNAL_IP4_MTU" up 2>>"$SESSION_DIR/script.log"
        else
            /sbin/ifconfig "$TUNDEV" inet "$INTERNAL_IP4_ADDRESS" "$INTERNAL_IP4_ADDRESS" \
                netmask "$INTERNAL_IP4_NETMASK" up 2>>"$SESSION_DIR/script.log"
        fi
    fi

    # 给 VPN 服务器本身加主机路由，避免环路。
    # 先删后加：上一轮会话异常退出（worker 是 SIGKILL，脚本的 disconnect 分支不会执行）
    # 可能残留一条陈旧主机路由，直接 add 会因 File exists 失败并沿用旧路由，
    # 旧路由绑定的源地址失效后会让本次连接直接报 Can't assign requested address。
    if [ -n "${VPNGATEWAY:-}" ] && [ -n "$ORIGINAL_GW" ]; then
        /sbin/route -n delete -host "$VPNGATEWAY" 2>/dev/null
        if [ "$ORIGINAL_GW" = "on-link" ]; then
            /sbin/route -n add -host "$VPNGATEWAY" -interface "${TUNDEV%%[0-9]*}0" 2>>"$SESSION_DIR/script.log"
        else
            /sbin/route -n add -host "$VPNGATEWAY" "$ORIGINAL_GW" 2>>"$SESSION_DIR/script.log"
        fi
    fi

    # DNS 要挂到物理网络服务上，得趁默认路由还指着物理网关时先认出它是谁
    if [ "$USE_VPN_DNS" = "1" ] && [ -n "${INTERNAL_IP4_DNS:-}" ]; then
        resolve_physical_service
    fi

    # 「以公司网络为主」：把默认路由从物理网关抢到隧道，公司流量才会真正走 VPN。
    # 顺序不能反——必须先加完 VPN 服务器的主机路由，再删默认路由，
    # 否则删掉默认路由的那一瞬间就失去了到 VPN 服务器的连通，隧道随即断裂。
    if [ "$SET_GATEWAY" = "1" ] && [ -n "${INTERNAL_IP4_ADDRESS:-}" ]; then
        if [ -n "$ORIGINAL_GW" ]; then
            /sbin/route -n delete default "$ORIGINAL_GW" 2>>"$SESSION_DIR/script.log"
        else
            /sbin/route -n delete default 2>>"$SESSION_DIR/script.log"
        fi
        /sbin/route -n add default "$INTERNAL_IP4_ADDRESS" 2>>"$SESSION_DIR/script.log"
        report default_route vpn
    fi

    # 真正把 VPN 下发 DNS 应用到本机。openconnect 建完隧道就不管 DNS 了，
    # 这一步必须由脚本自己做，否则公司内网域名永远解析不出来。
    # 必须排在默认路由接管之后：DNS 走隧道的前提是默认路由已经在隧道上。
    if [ "$USE_VPN_DNS" = "1" ] && [ -n "${INTERNAL_IP4_DNS:-}" ]; then
        # 原 /etc/resolv.conf 备份到会话目录，断开时还原（只备份第一次，脚本可能重复执行）
        if [ ! -f "$SESSION_DIR/resolv.conf.bak" ]; then
            /bin/cp /etc/resolv.conf "$SESSION_DIR/resolv.conf.bak" 2>/dev/null
        fi
        {
            echo '#@WS-TOOLS_GENERATED@'
            for ns in $INTERNAL_IP4_DNS; do
                echo "nameserver $ns"
            done
        } > /etc/resolv.conf 2>>"$SESSION_DIR/script.log"

        # 10.4 起 /etc/resolv.conf 对系统解析器基本失效，必须把 DNS 注册进
        # scutil 的网络服务状态，解析才会真正走 VPN 下发的 DNS。
        printf 'open\nd.init\nd.add ServerAddresses * %s\nset State:/Network/Service/%s/DNS\nd.init\nd.add Addresses * %s\nd.add SubnetMasks * 255.255.255.255\nd.add InterfaceName %s\nset State:/Network/Service/%s/IPv4\nclose\n' \
            "$INTERNAL_IP4_DNS" "$TUNDEV" "$INTERNAL_IP4_ADDRESS" "$TUNDEV" "$TUNDEV" \
            | /usr/sbin/scutil >/dev/null 2>&1

        # 新版 macOS 还要求把 DNS 写进当前物理网络服务本身
        if [ -n "$PHYSICAL_SERVICE" ]; then
            /usr/sbin/networksetup -setdnsservers "$PHYSICAL_SERVICE" $INTERNAL_IP4_DNS 2>>"$SESSION_DIR/script.log"
            report dns_service "$PHYSICAL_SERVICE"
        fi
        report dns_applied "${INTERNAL_IP4_DNS}"
    fi

    report done connect
    exit 0
fi

if [ "$reason" = "disconnect" ]; then
    report reason disconnect

    # 交还默认路由：不交还的话断开后整机既回不到本地网络也上不了公网。
    # 正常断开走的是脚本被调用，但 worker 侧是 SIGKILL，这条分支通常不会执行，
    # 真正的兜底在 worker 的 cleanup_routes 里，两边都要做。
    if [ "$SET_GATEWAY" = "1" ]; then
        /sbin/route -n delete default 2>>"$SESSION_DIR/script.log"
        if [ -n "$ORIGINAL_GW" ]; then
            /sbin/route -n add default "$ORIGINAL_GW" 2>>"$SESSION_DIR/script.log"
        fi
        report default_route local
    fi

    if [ -n "${VPNGATEWAY:-}" ]; then
        /sbin/route -n delete -host "$VPNGATEWAY" 2>>"$SESSION_DIR/script.log"
    fi
    if [ -n "${INTERNAL_IP4_ADDRESS:-}" ] && [ -n "${TUNDEV:-}" ]; then
        /sbin/ifconfig "$TUNDEV" inet "$INTERNAL_IP4_ADDRESS" remove 2>>"$SESSION_DIR/script.log"
    fi

    # 还原 DNS：默认路由已交还物理网关，此时才问得到正确的物理网络服务名。
    # 隧道是 SIGKILL 停的，这条分支通常不会执行，真正的兜底在 worker 的 cleanup_routes。
    if [ "$USE_VPN_DNS" = "1" ]; then
        resolve_physical_service
        if [ -f "$SESSION_DIR/resolv.conf.bak" ]; then
            /bin/cp "$SESSION_DIR/resolv.conf.bak" /etc/resolv.conf 2>>"$SESSION_DIR/script.log"
            /bin/rm -f "$SESSION_DIR/resolv.conf.bak"
        fi
        printf 'open\nremove State:/Network/Service/%s/DNS\nremove State:/Network/Service/%s/IPv4\nclose\n' \
            "${TUNDEV:-}" "${TUNDEV:-}" | /usr/sbin/scutil >/dev/null 2>&1
        if [ -n "$PHYSICAL_SERVICE" ]; then
            /usr/sbin/networksetup -setdnsservers "$PHYSICAL_SERVICE" Empty 2>>"$SESSION_DIR/script.log"
        fi
    fi

    report done disconnect
    exit 0
fi

exit 0
"#;

    body.replace("__MODE__", mode)
        .replace("__SET_GATEWAY__", set_gateway)
        .replace("__USE_VPN_DNS__", use_vpn_dns)
        .replace("__SESSION_DIR__", &session_dir)
        .replace("__ORIGINAL_GW__", &original_gw)
}

/// 生成当前平台对应的脚本，返回 (文件名, 内容)
pub fn generate(ctx: &ScriptContext) -> (&'static str, String) {
    #[cfg(target_os = "windows")]
    {
        ("vpnc-script-win.js", windows_script(ctx))
    }
    #[cfg(not(target_os = "windows"))]
    {
        ("vpnc-script.sh", macos_script(ctx))
    }
}

/// 断开时的兜底：把脚本改过的 DNS 还原回去。
///
/// 隧道是 SIGKILL 停掉的，脚本的 `disconnect` 分支不会执行，只能由 worker 在这里补一次：
/// 还原 `/etc/resolv.conf`、清掉 scutil 里挂在隧道网卡上的服务状态、把物理网络服务的
/// DNS 复位成「空」（即交回 DHCP/系统默认）。`network_service` 为空时只做前两步。
#[cfg(not(target_os = "windows"))]
pub fn restore_vpn_dns(session_dir: &Path, network_service: &str, tun_dev: &str) {
    use crate::process::run_with_timeout;
    use std::time::Duration;

    let backup = session_dir.join("resolv.conf.bak");
    if backup.is_file() {
        if std::fs::copy(&backup, "/etc/resolv.conf").is_ok() {
            let _ = std::fs::remove_file(&backup);
        }
    }

    // 网卡名由 openconnect 给出（形如 utun4），这里再过滤一遍，避免拼进 shell 时被注入
    let dev: String = tun_dev.chars().filter(|c| c.is_ascii_alphanumeric()).collect();
    if !dev.is_empty() {
        let command = format!(
            "printf 'open\\nremove State:/Network/Service/{dev}/DNS\\nremove State:/Network/Service/{dev}/IPv4\\nclose\\n' | /usr/sbin/scutil",
            dev = dev
        );
        let _ = run_with_timeout(
            Path::new("/bin/sh"),
            &["-c", &command],
            Duration::from_secs(10),
        );
    }

    if !network_service.is_empty() {
        let _ = run_with_timeout(
            Path::new("/usr/sbin/networksetup"),
            &["-setdnsservers", network_service, "Empty"],
            Duration::from_secs(10),
        );
    }
}

/// Windows 的 DNS 由 `vpnc-script-win.js` 自己管，这里不插手
#[cfg(target_os = "windows")]
pub fn restore_vpn_dns(_session_dir: &Path, _network_service: &str, _tun_dev: &str) {}

/// JScript 字符串转义：反斜杠和双引号
fn escape_js_string(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

/// shell 双引号内的转义
fn escape_sh_string(text: &str) -> String {
    text.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
        .replace('`', "\\`")
}

/// 从脚本回报的一行里解析键值对
pub fn parse_marker_line(line: &str) -> Option<(String, String)> {
    let rest = line.trim().strip_prefix(MARKER)?;
    let rest = rest.trim_start();
    let (key, value) = rest.split_once('=')?;
    Some((key.trim().to_string(), value.trim().to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx(mode: VpnMode, use_vpn_dns: bool) -> ScriptContext<'static> {
        ScriptContext {
            session_dir: Path::new(r"C:\Users\demo\AppData\Roaming\com.ws.tools\vpn"),
            mode,
            use_vpn_dns,
            original_gateway: "192.168.1.1",
        }
    }

    #[test]
    fn customer_first_does_not_take_default_route() {
        let script = windows_script(&ctx(VpnMode::CustomerFirst, false));
        assert!(script.contains(r#"var MODE = "customer_first";"#));
        // 客户网络为主：绝不设网关，否则 Windows 会自动加一条默认路由走 VPN
        assert!(script.contains("var SET_GATEWAY = false;"));
    }

    #[test]
    fn company_first_takes_default_route() {
        let script = windows_script(&ctx(VpnMode::CompanyFirst, false));
        assert!(script.contains(r#"var MODE = "company_first";"#));
        assert!(script.contains("var SET_GATEWAY = true;"));
        assert!(script.contains("gwmetric=1 store=active"));
    }

    #[test]
    fn dns_is_only_touched_when_enabled() {
        let off = windows_script(&ctx(VpnMode::CustomerFirst, false));
        assert!(off.contains("var USE_VPN_DNS = false;"));
        let on = windows_script(&ctx(VpnMode::CustomerFirst, true));
        assert!(on.contains("var USE_VPN_DNS = true;"));
        // validate=no 必须存在，否则 Windows 会先探测 DNS 可达性并卡约 10 秒
        assert!(on.contains("validate=no"));
    }

    #[test]
    fn windows_script_never_writes_persistent_config() {
        let script = windows_script(&ctx(VpnMode::CompanyFirst, true));
        assert!(script.contains("store=active"));
        assert!(!script.contains("store=persistent"));
    }

    #[test]
    fn windows_script_escapes_session_path() {
        let script = windows_script(&ctx(VpnMode::CustomerFirst, false));
        // 反斜杠必须被转义，否则 JScript 会把 \U 之类当成转义序列
        assert!(script.contains(r#"C:\\Users\\demo"#));
    }

    #[test]
    fn windows_script_adds_host_route_to_avoid_loop() {
        let script = windows_script(&ctx(VpnMode::CustomerFirst, false));
        assert!(script.contains("route add \" + vpngw + \" mask 255.255.255.255 "));
        assert!(script.contains(r#"var ORIGINAL_GW = "192.168.1.1";"#));
    }

    #[test]
    fn macos_script_uses_route_and_ifconfig() {
        let script = macos_script(&ctx(VpnMode::CustomerFirst, false));
        assert!(script.contains(r#"MODE="customer_first""#));
        assert!(script.contains("USE_VPN_DNS=0"));
        assert!(script.contains("/sbin/route -n add -host"));
        assert!(script.contains("/sbin/ifconfig"));
        assert!(script.starts_with("#!/bin/sh"));
    }

    #[test]
    fn macos_company_first_flag() {
        let script = macos_script(&ctx(VpnMode::CompanyFirst, true));
        assert!(script.contains("USE_VPN_DNS=1"));
        assert!(script.contains("SET_GATEWAY=1"));
    }

    #[test]
    fn macos_company_first_takes_default_route() {
        let script = macos_script(&ctx(VpnMode::CompanyFirst, false));
        // 接管默认路由是 company_first 唯一的实现方式：不接管就没有任何流量走隧道
        assert!(script.contains("/sbin/route -n delete default \"$ORIGINAL_GW\""));
        assert!(script.contains("/sbin/route -n add default \"$INTERNAL_IP4_ADDRESS\""));
        assert!(script.contains("report default_route vpn"));
    }

    #[test]
    fn macos_customer_first_keeps_physical_default_route() {
        let script = macos_script(&ctx(VpnMode::CustomerFirst, false));
        assert!(script.contains("SET_GATEWAY=0"));
    }

    #[test]
    fn macos_dns_is_applied_after_default_route() {
        let script = macos_script(&ctx(VpnMode::CompanyFirst, true));
        assert!(script.contains("USE_VPN_DNS=1"));
        // 光 report dns_applied 没用，必须真的写 resolv.conf / scutil / networksetup
        assert!(script.contains("resolve_physical_service"));
        assert!(script.contains("/usr/sbin/networksetup -setdnsservers"));
        assert!(script.contains("/usr/sbin/scutil"));
        assert!(script.contains("resolv.conf.bak"));
        assert!(script.contains("report dns_applied"));
        // 顺序是这套分流的命根子：默认路由先被隧道接管，DNS 再指过去
        let route_at = script.find("/sbin/route -n add default").unwrap();
        let dns_at = script.find("/usr/sbin/networksetup -setdnsservers").unwrap();
        assert!(
            dns_at > route_at,
            "DNS 必须排在默认路由接管之后，否则解析不走隧道"
        );
        // 认物理网络服务名必须趁默认路由还在物理网关上
        let resolve_at = script.find("resolve_physical_service\n").unwrap();
        assert!(resolve_at < route_at, "resolve_physical_service 必须先于默认路由接管");
    }

    #[test]
    fn macos_dns_is_runtime_guarded_by_flag() {
        // 脚本无论开关都会带上 DNS 机器码，靠运行期 USE_VPN_DNS 把关；
        // 关掉时一个 DNS 命令都不能执行。
        let off = macos_script(&ctx(VpnMode::CompanyFirst, false));
        assert!(off.contains("USE_VPN_DNS=0"));
        assert!(off.contains(r#"if [ "$USE_VPN_DNS" = "1" ]"#));
    }

    #[test]
    fn macos_disconnect_restores_dns() {
        let script = macos_script(&ctx(VpnMode::CompanyFirst, true));
        // disconnect 分支也要还原：交还默认路由后再拷回 resolv.conf 并清掉 networksetup
        assert!(script.contains("report default_route local"));
        assert!(script.contains("/usr/sbin/networksetup -setdnsservers \"$PHYSICAL_SERVICE\" Empty"));
    }

    #[test]
    fn windows_script_is_pure_ascii() {
        // cscript.exe 在没有 BOM 时按系统 ANSI 代码页（中文 Windows 即 GBK）解码 .js，
        // 一个非 ASCII 字节就会让整个脚本编译失败。这条断言是那个坑的唯一防线。
        for mode in [VpnMode::CustomerFirst, VpnMode::CompanyFirst] {
            for use_dns in [false, true] {
                let script = windows_script(&ctx(mode, use_dns));
                assert!(
                    script.is_ascii(),
                    "windows_script 必须只包含 ASCII 字符，否则 cscript 无法解析"
                );
            }
        }
    }

    #[cfg(target_os = "windows")]
    #[test]
    fn windows_script_compiles_under_cscript() {
        // 直接复现踩过的坑：脚本里只要混进一个非 ASCII 字节，cscript 就按系统
        // ANSI 代码页解码失败并退出 1，而 openconnect 只会把它曲解成
        // "Failed to spawn script"。所以这里真的把脚本交给 cscript 编译一遍。
        let dir = std::env::temp_dir().join("ws-tools-script-check");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("vpnc-script-win.js");

        for mode in [VpnMode::CustomerFirst, VpnMode::CompanyFirst] {
            std::fs::write(&path, windows_script(&ctx(mode, true))).unwrap();
            // reason 显式置空：脚本两个分支都不进，只会 WScript.Quit(0)，
            // 不会执行任何 netsh / route，动不到本机的网络配置。
            let output = std::process::Command::new("cscript.exe")
                .args(["//nologo", "//E:JScript"])
                .arg(&path)
                .env("reason", "")
                .output()
                .expect("cscript.exe 是 Windows 自带组件，应当可用");
            assert!(
                output.status.success(),
                "cscript 无法执行生成的脚本（{:?}）: {}{}",
                output.status,
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            );
        }

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn parse_marker_line_reads_key_value() {
        let (key, value) = parse_marker_line("WS-TOOLS ip4=192.168.137.39").unwrap();
        assert_eq!(key, "ip4");
        assert_eq!(value, "192.168.137.39");
    }

    #[test]
    fn parse_marker_line_keeps_spaces_in_value() {
        let (key, value) =
            parse_marker_line("WS-TOOLS dns=202.101.172.35 202.101.172.36").unwrap();
        assert_eq!(key, "dns");
        assert_eq!(value, "202.101.172.35 202.101.172.36");
    }

    #[test]
    fn parse_marker_line_ignores_other_output() {
        assert!(parse_marker_line("CSTP connected. DPD 90").is_none());
        assert!(parse_marker_line("").is_none());
    }
}
